-- Database Indexes for tracker_match Table
-- Generated by Django Migration 0002
-- Date: 2026-04-30

-- Index on map_id foreign key column
-- Improves queries filtering by map only
CREATE INDEX "tracker_match_map_id_191d03aa" ON "tracker_match" ("map_id");

-- Index on date column
-- Improves queries filtering by date only and date ordering
CREATE INDEX "tracker_match_date_c5876bb0" ON "tracker_match" ("date");

-- Compound index on (map_id, date)
-- Optimizes queries filtering by both map AND date
-- Also useful for queries filtering by map_id with date ordering
CREATE INDEX "tracker_mat_map_id_eb8d4d_idx" ON "tracker_match" ("map_id", "date");
